name: "Qodana analysis"

on: push

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: JetBrains/qodana-action@2b75b91f95751e06ff1341cae0869a9cfcc6bb10 # v2022.2.3
      - uses: github/codeql-action/upload-sarif@181d5eefc20863364f96762470ba6f862bdef56b # v3.29.2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
