name: "PHP analysis"

on:
  push:

jobs:
  PHP_CodeSniffer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Run Composer Install
        run: composer install
      - run: echo "::add-matcher::.github/problem-matcher.json"
      - name: Run PHPCS
        run: ./vendor/bin/phpcs --report=checkstyle --standard=./phpcs.xml ./src/PhpSample.php || true
  Psalm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Run Composer Install
        run: composer install
      - name: Run Psalm
        run: ./vendor/bin/psalm --output-format=github --no-cache || true
  PHP_Mess_Detector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Run Composer Install
        run: composer install
      - name: Run PHPMD
        run: vendor/bin/phpmd ./src/PhpSample.php github ./phpmd.xml || true
